name: Deploy to QA

on:
  push:
    branches:
      - qa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t roddroid/elb-implementation-app:latest .
          docker push roddroid/elb-implementation-app:latest

      - name: Deploy to QA instances
        run: |
          for instance in $(aws ec2 describe-instances --filters "Name=tag:Environment,Values=QA" --query "Reservations[*].Instances[*].PublicIpAddress" --output text); do
            ssh -o StrictHostKeyChecking=no -i my-key.pem ec2-user@$instance "docker pull roddroid/elb-implementation-app:latest && docker run -d -p 80:3000 roddroid/elb-implementation-app:latest"
          done
